version: 1.0.{build}-{branch}

image: Visual Studio 2017

shallow_clone: false
clone_depth: 5

environment:
  mpq_decryption_key:
    secure: pXIJzmDBCbR+oFPGeg3izuhDCv/rRSdtJd6wHSfQXuU=

install:
  - git submodule update --init --recursive
  - ps: >-
      if($isWindows) {
        nuget restore
      }
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - ps: Invoke-WebRequest 'https://n00byedge.com/mpqs/BrooDat.mpq.enc' -OutFile 'C:/projects/bwem-community/%CONFIGURATION%/BrooDat.mpq.enc'
  - ps: Invoke-WebRequest 'https://n00byedge.com/mpqs/StarDat.mpq.enc' -OutFile 'C:/projects/bwem-community/%CONFIGURATION%/StarDat.mpq.enc'
  - ps: Invoke-WebRequest 'https://n00byedge.com/mpqs/patch_rt.mpq.enc' -OutFile 'C:/projects/bwem-community/%CONFIGURATION%/patch_rt.mpq.enc'
  - cmd: appveyor-tools\secure-file -decrypt C:/projects/bwem-community/%CONFIGURATION%/BrooDat.mpq.enc -secret %mpq_decryption_key%
  - cmd: appveyor-tools\secure-file -decrypt C:/projects/bwem-community/%CONFIGURATION%/StarDat.mpq.enc -secret %mpq_decryption_key%
  - cmd: appveyor-tools\secure-file -decrypt C:/projects/bwem-community/%CONFIGURATION%/patch_rt.mpq.enc -secret %mpq_decryption_key%

build:
  project: BWEM.sln
  parallel: true

platform: x86

configuration:
  - Release
  - Debug

test_script:
  - ps: pushd %CONFIGURATION%
  - sh: ./tests --gtest_output=xml:"tests.xml"
  - cmd: '%CONFIGURATION%\Tests.exe --gtest_output=xml:"tests.xml"'
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests.xml))
  - ps: popd
